version: '3'

services:
  backend:
    build: .
    container_name: laravel-chat
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes: 
      - ./:/usr/share/nginx
    networks: 
      - backend-network
  
  db:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    networks: 
      - backend-network

networks: 
  backend-network:
    driver: bridge

volumes:
  dbdata:
    driver: local